data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data_subset <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")
date_time<-strptime(paste(data_subset$Date, data_subset$Time), format="%Y-%m-%d %H:%M:%S")
sub_metering_1 <- as.numeric(data_subset$Sub_metering_1)
sub_metering_2 <- as.numeric(data_subset$Sub_metering_2)
sub_metering_3 <- as.numeric(data_subset$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(date_time, sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(date_time, sub_metering_2, col="red")
lines(date_time, sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.off()